### ISSUE TITLE
Timeline .seek() doesn't execute the onComplete function

### ISSUE THREAD

**Issue by theoplawinski** [willybrauner/interpol#119]
Hello Willy!

In a project using React, I've created a basic Timeline.

Depending on the width of the screen, I `.play()` the Timeline or I go directly to the end of the animation using `.seek(1)`.

When I use `.play()`, the `onComplete` function is executed. However, when using `.seek(1)`, the `onComplete` does not execute.

Is this the expected behavior?

Thanks!

```typescript

const playInTimelineRef = useRef<Timeline>(null)
const isMinWidthTablet = useIsMinWidth("--breakpoint-tablet")

const initPlayInTimeline = (): Timeline => {
  return new Timeline({
    paused: true,
    onComplete: () => {
      console.log("play in complete")
    },
  })
  .add({ ... })
  .add({ ... })
  .add({ ... })
}

useIsomorphicLayoutEffect(() => {
  if (!playInTimelineRef.current) playInTimelineRef.current = initPlayInTimeline()
  isMinWidthTablet ? playInTimelineRef.current.play() : playInTimelineRef.seek(1)
}, [isMinWidthTablet])

```

**Comment by willybrauner** [comment]
This case is not covered yet, nice catch. Alternatively the last add() callback is executed on tl.seek(1), right? 

I gonna investigate on how to implement tl callbacks in case of seek.

**Comment by theoplawinski** [comment]
The last `.add()` callback is indeed executed on `tl.seek(1)`
